### ISSUE TITLE
Sometimes I get double items (offers/demands) after editing in list

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#85]
Try some new demands/offers and edit them. Sometimes it happens, that you have the item 2 times in the list.

**Comment by TIIUNDER** [comment]
It's gone after refreshing the list, but this is not a nice behavior

**Comment by GammaG** [comment]
redirect seems not to wait for my event. I made an hackaround like in removing, but would be better if redirect would wait for the event to finish. Eventually I have to create new EventTypes then. 
Now there might missing a entity in the list when an error happen. (It is there from backup but not shown eventually.)

**Comment by TIIUNDER** [comment]
It redirects after it gets the ServerResponseEvent (from BaseAsyncTask)

**Comment by GammaG** [comment]
mh but sometimes without the old one removed, how it seems :/

Well can you try again with my changes ?

**Comment by TIIUNDER** [comment]
problem still occurs

**Comment by GammaG** [comment]
I will look tomorrow ok

**Comment by TIIUNDER** [comment]
Ok, I tested it several times now and it worked. Maybe it's working now, but I'm not sure.

**Comment by TIIUNDER** [comment]
Stephan confirmed this bug

**Comment by stephanlindauer** [comment]
still buggy for offers

**Comment by stephanlindauer** [comment]
![screenshot_2015-07-27-23-07-07](https://cloud.githubusercontent.com/assets/1323145/8917783/7b84e3b0-34b4-11e5-8636-0c5652e383d1.png)

**Comment by GammaG** [comment]
meh, ok I will search tomorrow which side effect I don't see

**Comment by GammaG** [comment]
I just fixed this

**Comment by GammaG** [comment]
hope this time it works longer xD

**Comment by GammaG** [comment]
adapter seems not to clear correct, maybe a notify is missing?

**Comment by stephanlindauer** [comment]
please research .notifyDatasetChanged(); Tuesday, 28 July 2015, 10:39AM +02:00 from mseidler < notifications@github.com> :

**Comment by GammaG** [comment]
I think I fixed this, but please check again

**Comment by GammaG** [comment]
is checked works now. It was "notifyDatasetChanged" but the other way. It existed and had to be removed.

**Comment by TIIUNDER** [comment]
Nope, problem still occurs

![screenshot_2015-07-28-20-46-21](https://cloud.githubusercontent.com/assets/1225378/8940376/e377f254-3569-11e5-8a5a-41950c70cce9.png)

**Comment by TIIUNDER** [comment]
Also, reloading the list now keeps double items.

**Comment by TIIUNDER** [comment]
Reloading the offer list refreshes it correct and removes double item. But demand list not.

**Comment by GammaG** [comment]
![bibjb](https://cloud.githubusercontent.com/assets/2648086/8951667/ecb44280-35cf-11e5-8b5d-07895dfb12d8.PNG)
I just checked this, here I edited "tune up" and it is just one time in the list. Nevertheless I get it displayed twice. I have no idear anymore ..

**Comment by GammaG** [comment]
I just tried to clear the adapter and to add the list again and change notifies location. But no use either not displayed at all or no changes. @TIIUNDER @stephanlindauer if you guys have an idear feel free to try. It is not the list the values are valid, must be something about the view.

**Comment by GammaG** [comment]
@TIIUNDER the only possibility is that some of you adapters has a problem.

**Comment by GammaG** [comment]
I replaced that with an other problem, but I think the problem is again the redirect comes before the result is there. @TIIUNDER  maybe you can take a look?

**Comment by GammaG** [comment]
can we redirect that to details view maybe ? Then we can get that by getById

**Comment by stephanlindauer** [comment]
did none of those things work: https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=double%20items%20android%20adapter%20list

**Comment by stephanlindauer** [comment]
?

**Comment by GammaG** [comment]
I made some tries, changed the way the ArrayAdapter fills in the information. Seems to work now, but please test this on your devices. @stephanlindauer @TIIUNDER

**Comment by TIIUNDER** [comment]
For offers it seems to work, but demands is still buggy. Please check this comment https://github.com/neeedo/neeedo-android/issues/85#issuecomment-125713772

Since that comment there is a problem that also reloading the list doesn't help 

![screenshot_2015-07-29-16-09-48](https://cloud.githubusercontent.com/assets/1225378/8959691/8d4975bc-360c-11e5-965f-73d6d20411c2.png)

**Comment by stephanlindauer** [comment]
also @GammaG remember yesterday when i told you why you should not call notifyDataSetChanged() before you you assigned the adapter to a list?

**Comment by GammaG** [comment]
that wasn't what was wrong. I now use an other style.

**Comment by GammaG** [comment]
seems to be fixed - this time for real

**Comment by stephanlindauer** [comment]
what kind of style is that? the way you are using the custom adapter is wrong.

**Comment by stephanlindauer** [comment]
loading spinner is still broken. please fix.

**Comment by TIIUNDER** [comment]
@stephanlindauer How and where do you get this issue? I can not reproduce this

**Comment by TIIUNDER** [comment]
Ok, I have the same problem, loading an empty list shows message and spinner

**Comment by stephanlindauer** [comment]
just load an empty demands or offers list

**Comment by GammaG** [comment]
ah yeah I know why this happens

**Comment by GammaG** [comment]
I made the changes, should work now.
